- name: Ading grafana repo
  ansible.builtin.yum_repository:
    name: grafana
    baseurl: https://rpm.grafana.com
    description:  Grafana repository for 5.x packages
    gpgkey: https://rpm.grafana.com/gpg.key
    gpgcheck: true
    enabled: yes
    sslverify: true
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt    

- name: Adding Repo
  ansible.builtin.yum:
    name: grafana
    state: present

# - name: Install grafana
#   ansible.builtin.yum:
#     name: https://dl.grafana.com/oss/release/grafana-{{ version }}-1.x86_64.rpm
#     state: present

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Grafana server started"
  service:
    name: grafana-server
    enabled: true
    state: started

- name: "Check if Grafana is accessible."
  uri:
    url: http://127.0.0.1:3000
    method: GET
    status_code: 200
